# Generated by Django 6.0 on 2025-12-27 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0004_user_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 28, 18, 46, 43, 267886, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
