# Generated by Django 6.0 on 2025-12-27 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comptes", "0005_user_token_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token_created_at",
        ),
        migrations.AddField(
            model_name="user",
            name="token_expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 28, 19, 14, 7, 156564, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
